### ISSUE TITLE
MySQL Decimal type is cast as a string

### ISSUE THREAD

**Issue by Donkie** [syl0r/MySQLOO#8]
Not sure if this is intended to preserve precision.
I expected this type to be cast as a regular lua number and not a string.

https://github.com/syl0r/MySQLOO/blob/master/MySQLOO/source/Query.cpp#L166
https://dev.mysql.com/doc/refman/5.7/en/fixed-point-types.html

**Comment by syl0r** [comment]
The problem is that MySQL's decimals are very different to lua's double. So in the use cases where you'd want to use a decimal, it'd be very bad to cast it to a double since you'll lose all that precision.

If you want to get it as double you can just cast it to a double in the query SELECT (CAST field AS DOUBLE) ...

**Comment by Kefta** [comment]
How do the precisions compare?

**Comment by Donkie** [comment]
I understand. Makes sense to keep it the way it is then.
